# frozen_string_literal: true

source 'https://rubygems.org'

gem 'xui-form', path: '.'

gem 'xikolo-config', path: '../xikolo-config'

group :development, :test do
  gem 'actionpack'
  gem 'rake'
  gem 'restify', '~> 2.0'
  gem 'rspec', '~> 3.10'
  gem 'rspec_junit_formatter', '~> 0.6.0', require: false
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
end
