# frozen_string_literal: true

# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically
# be available to Rake.
require_relative 'config/application'

Xikolo::Account::Application.load_tasks

task(:default).clear.enhance %i[spec]

namespace :ci do
  desc 'Setup service for CI'
  task setup: %w[db:drop:all db:create:all db:schema:load]

  desc 'Run specs for CI'
  task spec: %w[^default]
end
