# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.4.0'

# Rails
gem 'rails', '~> 7.2.0'

gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'drb'
gem 'json'
gem 'mutex_m'
gem 'ostruct'
gem 'syslog'

gem 'concurrent-ruby', '~> 1.0'
gem 'scientist', '~> 1.0'
gem 'vernier'                   # vernier must be required before Sentry
gem 'sentry-rails', '~> 5.26.0' # rubocop:disable Bundler/OrderedGems
gem 'sentry-ruby', '~> 5.26.0'
gem 'sentry-sidekiq', '~> 5.26.0'
gem 'telegraf', '~> 3.0'

# API
gem 'api-responder'
gem 'decorate-responder', '~> 2.0'
gem 'draper', '~> 4.0'
gem 'groupdate', '~> 6.0'
gem 'http_accept_language'
gem 'paginate-responder', '~> 2.0'
gem 'rails-rfc6570', '~> 3.0'
gem 'responders'
gem 'will_paginate'

gem 'oj', platform: :ruby

gem 'acts_as_list'
gem 'awesome_nested_set', '~> 3.4'
gem 'uuid4', '~> 1.4'

# Messaging via RabbitMQ
gem 'msgr', '~> 1.5'

gem 'restify', '~> 2.0'
gem 'xikolo-common', path: './gems/xikolo-common'
gem 'xikolo-config', path: './gems/xikolo-config'
gem 'xikolo-s3', path: './gems/xikolo-s3'
gem 'xikolo-sidekiq', path: './gems/xikolo-sidekiq'

gem 'course_service', path: 'engines/course_service'

# Versioning of ActiveRecords
gem 'paper_trail', '~> 16.0'

# Data storage
gem 'activerecord-postgres_enum', '~> 2.0'
gem 'fx', '~> 0.9.0'
gem 'pg', '~> 1.0'
gem 'redis', '~> 5.0'
gem 'scenic', '~> 1.5'

# App servers
gem 'puma'
gem 'thruster'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'listen', '~> 3.9.0'
end

group :test do
  gem 'accept_values_for'
  gem 'factory_bot_rails', '~> 6.0'
  gem 'timecop'
  gem 'uuidtools'
  gem 'webmock'

  gem 'rspec', '~> 3.10'
  gem 'rspec-collection_matchers'
  gem 'rspec-github', '~> 3.0', require: false
  gem 'rspec-its'
  gem 'rspec_junit_formatter', '~> 0.6.0', require: false
  gem 'rspec-rails', '~> 8.0'
end

group :test, :integration do
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
end

group :integration do
  gem 'rack-remote'
end
