# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.4.0'

gem 'rails', '~> 7.2.0'

gem 'drb'
gem 'json'
gem 'mutex_m'
gem 'ostruct'
gem 'syslog'

gem 'decorate-responder'
gem 'draper', '~> 4.0'
gem 'has_scope', '~> 0.8.0'

gem 'rails-rfc6570', '~> 3.0'
gem 'responders', '~> 3.0'

gem 'timeeffort_service', path: 'engines/timeeffort_service'

gem 'msgr', '~> 1.5'
gem 'restify', '~> 2.0'
gem 'uuid4', '~> 1.4'

# Data storage
gem 'activerecord-postgres_enum', '~> 2.0'
gem 'fx', '~> 0.9.0'
gem 'pg'
gem 'redis', '~> 5.0'
gem 'scenic', '~> 1.5'

gem 'xikolo-common', path: './gems/xikolo-common'
gem 'xikolo-config', path: './gems/xikolo-config'
gem 'xikolo-sidekiq', path: './gems/xikolo-sidekiq'

gem 'concurrent-ruby', '~> 1.0'
gem 'stackprof'                 # stackprof must be required before Sentry
gem 'sentry-rails', '~> 5.26.0' # rubocop:disable Bundler/OrderedGems
gem 'sentry-ruby', '~> 5.26.0'
gem 'sentry-sidekiq', '~> 5.26.0'
gem 'telegraf', '~> 3.0'

gem 'activejob-cancel', '~> 0.3'

# For RichText time effort calculation
gem 'redcarpet', '~> 3.4'

# App servers
gem 'puma'
gem 'thruster'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'listen', '~> 3.9.0'
end

group :test do
  gem 'accept_values_for'
  gem 'factory_bot_rails', '~> 6.0'
  gem 'timecop'
  gem 'typhoeus', require: false
  gem 'webmock', require: false

  gem 'rspec', '~> 3.10'
  gem 'rspec-github', '~> 3.0', require: false
  gem 'rspec_junit_formatter', '~> 0.6.0', require: false
  gem 'rspec-rails', '~> 8.0'
end

group :test, :integration do
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
end

group :integration do
  gem 'rack-remote'
end
