# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.3.0'

gem 'rails', '~> 6.1.0'
gem 'sprockets', '~> 3.2'
gem 'sprockets-rails', '~> 3.2'

gem 'drb'
gem 'json'
gem 'mutex_m'
gem 'syslog'

gem 'decorate-responder'
gem 'draper', '~> 4.0'
gem 'has_scope', '~> 0.8.0'

gem 'rails-rfc6570', '~> 3.0'
gem 'responders', '~> 3.0'

gem 'msgr', '~> 1.5'
gem 'restify', '~> 1.15'
gem 'uuid4', '~> 1.4'

# Data storage
gem 'activerecord-postgres_enum', '~> 2.0'
gem 'fx', '~> 0.8.0'
gem 'pg'
gem 'redis', '~> 5.0'
gem 'scenic', '~> 1.5'

gem 'xikolo-common', path: './gems/xikolo-common'
gem 'xikolo-config', path: './gems/xikolo-config'
gem 'xikolo-sidekiq', path: './gems/xikolo-sidekiq'

gem 'concurrent-ruby', '~> 1.0'
gem 'mnemosyne-ruby', '~> 2.0'
gem 'sentry-rails', '~> 5.22.0'
gem 'sentry-ruby', '~> 5.22.0'
gem 'sentry-sidekiq', '~> 5.22.0'
gem 'telegraf', '~> 3.0'

gem 'activejob-cancel', '~> 0.3'

# For RichText time effort calculation
gem 'redcarpet', '~> 3.4'

# App servers
gem 'puma'

group :test do
  gem 'accept_values_for'
  # https://github.com/thoughtbot/factory_bot_rails/pull/432
  gem 'factory_bot_rails', '~> 6.0'
  gem 'rspec', '~> 3.10'
  gem 'rspec-teamcity'
  gem 'typhoeus', require: false
  gem 'webmock', require: false
end

group :development, :test do
  gem 'listen', '~> 3.9.0'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-rails', '~> 6.0'
  gem 'timecop'
end

group :test, :integration do
  gem 'database_cleaner', '~> 2.0'
  gem 'simplecov'
  gem 'simplecov-teamcity-summary'
end

group :integration do
  gem 'rack-remote'
end
