---
name: Set up node
description: Install native deps, Ruby, and Gems

inputs:
  working-directory:
    description: "The working directory to use for resolving paths for .ruby-version, .tool-versions, mise.toml and Gemfile.lock."

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo apt-get --quiet --quiet update
        sudo apt-get --quiet --quiet --option Dpkg::Use-Pty=0 install $(cat packages.txt)

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
