# frozen_string_literal: true

source 'https://rubygems.org'

gem 'xikolo-common', path: '.'

group :development, :test do
  gem 'rake'
  gem 'rspec'
  gem 'rspec-its'
  gem 'rspec_junit_formatter', '~> 0.6.0', require: false
end

group :test do
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
  gem 'webmock'
end
