# frozen_string_literal: true

source 'https://rubygems.org'

gem 'xikolo-common', path: '.'

group :development, :test do
  gem 'rake'
  gem 'rspec'
  gem 'rspec-its'
end

group :test do
  gem 'simplecov'
  gem 'webmock'
end
