---
include:
  - path: compose.background.yml
  - path: compose.account.yml
  - path: compose.collabspace.yml
  - path: compose.course.yml
  - path: compose.grouping.yml
  - path: compose.news.yml
  - path: compose.notification.yml
  - path: compose.pinboard.yml
  - path: compose.quiz.yml
  - path: compose.timeeffort.yml
  - path: compose.web.yml

services:
  nginx:
    image: registry.xikolo.de/xikolo/web/xikolo-nginx:latest
    volumes:
      - ./config/support/server.conf:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      NGINX_ENTRYPOINT_LOCAL_RESOLVERS: "true"
    networks:
      - xikolo
    ports:
      - 8000:80
      - 8443:443
