# frozen_string_literal: true

class ChangePrimaryKeysToUuid7 < ActiveRecord::Migration[6.1]
  def change
    change_column_default :abuse_reports, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :additional_quiz_attempts, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :alerts, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :announcements, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :answers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :assignment_rules, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :authorizations, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :badges, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :banners, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :branches, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :calendar_events, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :channels, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :classifiers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :client_applications, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :collab_space_memberships, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :collab_spaces, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :comments, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :conflicts, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :consents, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :content_tests, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :contexts, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :course_offers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :course_providers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :course_set_relations, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :course_sets, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :course_visuals, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :courses, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :custom_field_values, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :custom_fields, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :deliveries, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :document_localizations, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :documents, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :emails, :uuid, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :enrollments, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :events, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :file_versions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :files, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :filters, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :flippers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :forks, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :gallery_votes, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :grades, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :grants, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :groups, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :item_results, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :items, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :knowledge_acquisitions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :knowledge_examinations, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :learning_units, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :live_events, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :lti_exercises, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :lti_gradebooks, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :lti_grades, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :lti_providers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :mail_logs, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :memberships, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :messages, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :metadata, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :metrics, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :news, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :news_emails, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :news_translations, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :nodes, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :notes, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :notifications, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :objectives, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :objectives_items, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :open_badge_templates, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :open_badges, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :pages, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :participants, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :peer_assessment_files, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :peer_assessment_groups, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :peer_assessments, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :pinboards, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :policies, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :poll_options, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :poll_responses, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :polls, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :progresses, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :providers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :question_statistics, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :questions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :quiz_answers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :quiz_questions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :quiz_submission_answers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :quiz_submission_questions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :quiz_submission_snapshots, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :quiz_submissions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :quizzes, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :read_states, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :records, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :results, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :reviews, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :richtexts, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :roles, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :rubric_options, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :rubrics, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :scores, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :sections, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :sessions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :shared_submissions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :steps, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :streams, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :submission_files, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :submissions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :subscriptions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :subtitle_cues, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :subtitles, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :tags, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :teachers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :templates, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :test_groups, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :thumbnails, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :tickets, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :time_effort_items, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :time_effort_jobs, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :tokens, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :treatments, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :trial_results, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :trials, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :user_objectives, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :user_statuses, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :user_tests, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :users, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :versions, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :videos, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :votes, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :vouchers, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
    change_column_default :watches, :id, from: -> { 'gen_random_uuid()' }, to: -> { 'uuid_generate_v7ms()' }
  end
end
