---
name: lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  editorconfig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  js:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn run lint:js --color

  css:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn run lint:css --color

  markdown:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn run lint:md

  # Check that all files are correctly formatted. Use `yarn run format`
  # to auto-format all files.
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: yarn run lint:format

  rubocop:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ruby
      - run: bundle exec rubocop --color -f github -f progress

  slim:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ruby
      - run: bundle exec slim-lint -r github ./app/**/*.slim

  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        id: actionlint
        uses: raven-actions/actionlint@v2

  complete:
    if: always()

    needs:
      - actionlint
      - css
      - editorconfig
      - format
      - js
      - markdown
      - rubocop
      - slim

    runs-on: ubuntu-24.04

    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
