---
name: Stale Branches

on:
  schedule:
    - cron: "0 6 * * 1-5"

permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
      - uses: crs-k/stale-branches@v7.0.0
